name: continuous integration
on: [push]
jobs:
 Build:
    runs-on: ubuntu-latest
    steps:
      - name: cache Node Modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-cache

      - name: checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/checkout@v1
        with:
         node-version: 16.x

      - name: Install Dependencies
        run: cd backend && npm ci

      - name: Build
        run: cd backend && npm run build

      - name: Generate Artifcat
        run: cd backend/build && zip -r artifact.zip ./ `*.git*`

      - name: Store Artifact
        uses: actions/upload-artifact@v2
        with:
         name: backend-artifact
         path: backend/build/artifact.zip
 Lint:
  needs: [Build]
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: cache Node Modules
      id: cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node-modules-cache

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != true
      run: cd backend && npm ci

    - name: Lint the code 
      run: cd backend && npm run lint
 Test:
  needs: [Build]
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: cache Node Modules
      id: cache
      uses: actions/cache@v2
      with:
       path: node_modules
       key: node-modules-cache


    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != true
      run: cd backend && npm ci

    - name: Run Unit Test
      run: cd backend && npm t

 Security-audit:
  needs: [Build]
  runs-on: [ubuntu-latest]
  steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: Check For Security Issues
      run: cd backend && npm audit --audit-level=moderate

    - name: Fix Security Audit
      run: cd backend && npm audit fix


 


