name: continuous integration
on: [push]
jobs:
 compile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - run: cd backend
      - run: npm i
      - run: npm build