name: continuous integration
on: [push]
jobs:
 compile:
    runs-on: ubuntu-latest
    steps:
      - name: cache Node Modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-cache

      - name: checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/checkout@v1
        with:
          node-version: 16.x

      - name: Install Dependencies
        run: cd backend && npm ci

      - name: Build
        run: cd backend && npm run build

      - name: Generate Artifcat
        run: cd backend/build && zip -r artifact.zip ./ `*.git*`

      - name: Store Artifact
        uses: actions/upload-artifact@v2
        with:
         name: backend-artifact
         path: backend/build/artifact.zip